@startuml
!include estilo.iuml
skinparam defaultFontSize 13

object "<u>ana Usuario</u>" as ana {
  nomeUsuario = "ana.moedas"
  situacao = Ativa
}
object "<u>bruno Usuario</u>" as bruno {
  nomeUsuario = "bruno_numismata"
  situacao = Ativa
}
object "<u>moedas Categoria</u>" as moedas {
  nome = "Moedas"
}
object "<u>imperio Colecao</u>" as colA {
  nome = "Moedas do Império"
  visibilidade = Publica
}
object "<u>colonia Colecao</u>" as colB {
  nome = "Brasil Colônia"
  visibilidade = Publica
}
object "<u>patacao Item</u>" as itemA {
  nome = "Patacão 960 Réis 1815"
  estado = MuitoBom
  disponivelParaTroca = true
}
object "<u>milreis Item</u>" as itemB {
  nome = "1000 Réis 1851"
  estado = Excelente
  disponivelParaTroca = true
}
object "<u>fotoPatacao Foto</u>" as foto {
  posicao = 1
  situacao = Pronta
}
object "<u>proposta42 PropostaTroca</u>" as prop {
  situacao = Aceita
  enviadaEm = 12/10/2026
}
object "<u>ofertado ItemProposta</u>" as ip1 {
  parte = "Proponente"
}
object "<u>pedido ItemProposta</u>" as ip2 {
  parte = "Destinatario"
}

ana -- colA
bruno -- colB
colA -- moedas
colB -- moedas
colA -- itemA
itemA -- foto
colB -- itemB
ana -- prop : proponente
bruno -- prop : destinatário
prop -- ip1
prop -- ip2
ip1 -- itemA
ip2 -- itemB
@enduml
